#~ Topics for publishing/subscribing

occupancy_grid_publish_topic : /slam/map
robot_trajectory_publish_topic : /robot_trajectory
trajectory_publisher_frame_id : map
laser_subscriber_topic : /laser/scan

#~ Tf frames 

world_frame : world
base_footprint_frame : base_footprint
base_frame : base_link
map_frame : map
laser_frame : laser_link

#~ SLAM parameters

hill_climbing_disparity : 40
# slam_container_size : 500
slam_container_size : 900
# slam_occupancy_grid_dimentionality : 0.02
slam_occupancy_grid_dimentionality : 0.012
map_update_density : 30
map_update_obstacle_density : 3.0
scan_density_lower_boundary : 0.3
# max_hill_climbing_iterations : 40000
max_hill_climbing_iterations : 70000
desired_number_of_picked_rays : 50

#~ Publishing frequencies (Hz)

occupancy_grid_map_freq : 1.0
robot_pose_tf_freq : 6.0
trajectory_freq : 1.0

#~ Robot parameters

robot_width : 0.6
robot_length : 0.75
